config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  get 'my_record', to: 'home#my_record'
  get 'columns', to: 'home#columns'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  enum is_type: [
    :morning,
    :lunch,
    :dinner,
    :snack 
  ]
end

app/models/column.rb
class Column < ApplicationRecord
end

app/models/exer.rb
class Exer < ApplicationRecord
  belongs_to :user

  enum is_type: {
    day: 0,
    week: 1
  }
end

app/models/my_record.rb
class MyRecord < ApplicationRecord
  belongs_to :user

  enum is_type: {
    day: 0,
    week: 1
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :exers
  has_many :my_records
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < BaseController
  skip_before_action :authenticate_user!, only: [:columns]

  def index
    @mornings = Category.where(is_type: :morning).order(created_at: :desc)
    @lunchs = Category.where(is_type: :lunch).order(created_at: :desc)
    @dinners = Category.where(is_type: :dinner).order(created_at: :desc)
    @snacks = Category.where(is_type: :snack).order(created_at: :desc)
  end

  def my_record
    my_record = Exer.includes(:user)
      .where(user_id: current_user.id)

    @days = my_record.where(is_type: :day).order(created_at: :desc)
    @weeks = my_record.where(is_type: :week).order(created_at: :desc)

    @diaries = MyRecord.includes(:user)
      .where(user_id: current_user.id)
      .order(created_at: :desc)
  end

  def columns
    @columns = Column.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(test_path)
    return 'active' if request.path == test_path
    ''
  end
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/columns.html.slim
- titles = [ \
  {title: 'RECOMMENDED COLUMN', desc: 'オススメ'},
  {title: 'RECOMMENDED DIET', desc: 'ダイエット'},
  {title: 'RECOMMENDED BEAUTY', desc: '美容'},
  {title: 'RECOMMENDED HEALTH', desc: '健康'}]

section.recomment
  .container
    .row
      - titles.each do |item|
        .col-lg-3
          .item
            h4 = item[:title]
            hr
            p = item[:desc]
section#column.column
  .container
    .row.gy-4
      - ids = @columns.limit(8).pluck(:id)
      - new_columns = @columns.where.not(id: ids)
      - @columns.limit(8).each do |item, i|
        .col-lg-3.col-md-6
          .item
            = link_to "#", class: "" do
              = image_tag "#{item.img}"
            h4 = item.title
            p.desc = item.description
    #new-column.d-none style="margin-top: 10px;"
      .row.gy-4
        - new_columns.each do |column|
          .col-lg-3.col-md-6
            .item
              = link_to "#", class: "" do
                = image_tag "#{column.img}"
              h4 = column.title
              p.desc = column.description
    .row.justify-content-between
      .col-md-12.text-center.align-items-center
        button.btn-more.mt-30 記録をもっと見る

app/views/home/index.html.slim
section#get-started.get-started.section-home
  .row.justify-content-between
    .col-lg-5.d-flex.align-items-center.mr-reset
      .home-bg
        = image_tag "contents/main_photo.svg"
    .col-lg-7.content
      - chart = [ \
          {name: "a", data: [["06", 10], ["07", 9], ["08", 8], ["09", 8], ["10", 7], ["11", 6], ["12", 4], ['01', 4], ['02', 2], ['03', 2], ['04', 4], ['05', 2]]},
          {name: "b", data: [["06", 7], ["07", 9], ["08", 3], ["09", 4], ["10", 6], ["11", 3], ["12", 5], ['01', 6], ['02', 3], ['03', 4], ['04', 5], ['05', 4]]}]
      = line_chart chart

section#constructions.dinner.mt-30
  .container
    .row.justify-content-between
      .col-md-12.text-center.align-items-center
        ul#pills-tab.nav.nav-pills.mb-3.list-inline.mx-auto.justify-content-center role="tablist"
          li.nav-item role="presentation"
            = link_to root_path('type': 'morning'), {'data-bs-toggle': 'pill', 'data-bs-target': '#morning', 'role': 'tab', "aria-controls": "pills-home", "aria-selected": "true", class: "active"}
              = image_tag "icons/icon_morning.svg"
          li.nav-item role="presentation"
            = link_to root_path('type': 'lunch'), {'data-bs-toggle': 'pill', 'data-bs-target': '#lunch', 'role': 'tab', "aria-controls": "pills-home", "aria-selected": "true"}
              = image_tag "icons/icon_lunch.svg"
          li.nav-item role="presentation"
            = link_to root_path('type': 'dinner'), {'data-bs-toggle': 'pill', 'data-bs-target': '#dinner', 'role': 'tab', "aria-controls": "pills-home", "aria-selected": "true"}
              = image_tag "icons/icon_dinner.svg"
          li.nav-item role="presentation"
            = link_to root_path('type': 'snack'), {'data-bs-toggle': 'pill', 'data-bs-target': '#snack', 'role': 'tab', "aria-controls": "pills-home", "aria-selected": "true"}
              = image_tag "icons/icon_snack.svg"

      #pills-tabContent.tab-content
        #morning.tab-pane.fade.show.active role="tabpanel" aria-labelledby="morning-tab"
          .row.gy-4.portfolio-container
            - more_ids = @mornings.limit(8).pluck(:id)
            - new_mornings = @mornings.where.not(id: more_ids)

            - @mornings.limit(8).each do |item|
              .col-lg-3.col-md-6.portfolio-item.filter-remodeling
                .portfolio-content.h-100
                  = image_tag "#{item.img}", class: 'img-fluid', alt: "#{item.title}"
                  .portfolio-info
                    h4 = item.title
          #new-morn.d-none
            .row.gy-4
              - new_mornings.each do |item|
                .col-lg-3.col-md-6.portfolio-item.filter-remodeling
                  .portfolio-content.h-100
                    = image_tag "#{item.img}", class: 'img-fluid', alt: "#{item.title}"
                    .portfolio-info
                      h4 = item.title
          .row.justify-content-between
            .col-md-12.text-center.align-items-center
              button#tbn-morn.btn-more 記録をもっと見る
        #lunch.tab-pane.fade[role="tabpanel" aria-labelledby="lunch-tab"]
          .row.gy-4.portfolio-container
            - lunch_ids = @lunchs.limit(8).pluck(:id)
            - new_lunchs = @lunchs.where.not(id: lunch_ids)
            - @lunchs.limit(8).each do |item|
              .col-lg-3.col-md-6.portfolio-item.filter-remodeling
                .portfolio-content.h-100
                  = image_tag "#{item.img}", class: 'img-fluid', alt: "#{item.title}"
                  .portfolio-info
                    h4 = item.title
          #new-lunch.d-none
            .row.gy-4
              - new_lunchs.each do |item|
                .col-lg-3.col-md-6.portfolio-item.filter-remodeling
                  .portfolio-content.h-100
                    = image_tag "#{item.img}", class: 'img-fluid', alt: "#{item.title}"
                    .portfolio-info
                      h4 = item.title
          .row.justify-content-between
            .col-md-12.text-center.align-items-center
              button#tbn-lunch.btn-more 記録をもっと見る
        #dinner.tab-pane.fade[role="tabpanel" aria-labelledby="dinner-tab"]
          .row.gy-4.portfolio-container
            - dinner_ids = @dinners.limit(8).pluck(:id)
            - new_dinners = @dinners.where.not(id: dinner_ids)
            - @dinners.limit(8).each do |item|
              .col-lg-3.col-md-6.portfolio-item.filter-remodeling
                .portfolio-content.h-100
                  = image_tag "#{item.img}", class: 'img-fluid', alt: "#{item.title}"
                  .portfolio-info
                    h4 = item.title
          #new-dinner.d-none
            .row.gy-4.portfolio-container
              - new_dinners.each do |item|
                .col-lg-3.col-md-6.portfolio-item.filter-remodeling
                  .portfolio-content.h-100
                    = image_tag "#{item.img}", class: 'img-fluid', alt: "#{item.title}"
                    .portfolio-info
                      h4 = item.title
          .row.justify-content-between
            .col-md-12.text-center.align-items-center
              button#tbn-dinner.btn-more 記録をもっと見る
        #snack.tab-pane.fade[role="tabpanel" aria-labelledby="snack-tab"]
          .row.gy-4.portfolio-container
            - snack_ids =  @snacks.limit(8).pluck(:id)
            - new_snacks = @snacks.where.not(id: snack_ids)
            - @snacks.limit(8).each do |item|
              .col-lg-3.col-md-6.portfolio-item.filter-remodeling
                .portfolio-content.h-100
                  = image_tag "#{item.img}", class: 'img-fluid', alt: "#{item.title}"
                  .portfolio-info
                    h4 = item.title
            #new-snack.d-none
              .row.gy-4.portfolio-container
                - new_snacks.each do |item|
                  .col-lg-3.col-md-6.portfolio-item.filter-remodeling
                    .portfolio-content.h-100
                      = image_tag "#{item.img}", class: 'img-fluid', alt: "#{item.title}"
                      .portfolio-info
                        h4 = item.title
          .row.justify-content-between
            .col-md-12.text-center.align-items-center
              button#tbn-snack.btn-more 記録をもっと見る

app/views/home/my_record.html.slim
- datas = [ \
    {title: 'BODY RECORD', id: '#record', desc: '自分のカラダの記録'},
    {title: 'MY EXERCISE', id: '#exercise', desc: '自分の運動の記録'},
    {title: 'MY DIARY', id: '#diary', desc: '自分の日記'}]

section.my_reocde.mb-50.mt-30
  .container
    .row.justify-content-between
      - datas.each do |item|
        .col-lg-4
          .item.item_1.align-items-center
            = link_to "#{item[:title]}", "#{item[:id]}"
            p = item[:desc]
section#record.mb-50.mt-30
  .container
    .my_exercise.chart
      .row
        .col-md-1
          | MY
          br
          | RECORD
        .col-md-11
          = Time.current.strftime('%Y.%m.%d')
      .row
        .col-md-12
          / TODO:
          - chart = [ \
            {name: "a", data: [["06", 10], ["07", 9], ["08", 8], ["09", 8], ["10", 7], ["11", 6], ["12", 4], ['01', 4], ['02', 2], ['03', 2], ['04', 4], ['05', 2]]},
            {name: "b", data: [["06", 7], ["07", 9], ["08", 3], ["09", 4], ["10", 6], ["11", 3], ["12", 5], ['01', 6], ['02', 3], ['03', 4], ['04', 5], ['05', 4]]}]
          = line_chart chart
section#exercise.mb-50
  .container
    .my_exercise
      .row
        .col-md-1
          | MY
          br
          | EXERCISE
        .col-md-11
          = Time.current.strftime('%Y.%m.%d')
      .row
        .col-md-6
          table
            tbody
              - @days.each do |item|
                tr
                  td.w-90
                    p.desc = "● #{item.title}"
                    p.kcal = "#{item.number}kcal"
                  td.w-10
                    p.time
                      | 10 min
        .col-md-6
          table
            tbody
              - @weeks.each do |item|
                tr
                  td.w-90
                    p.desc = "● #{item.title}"
                    p.kcal = "#{item.number}kcal"
                  td.w-10
                    p.time = '10 min'
      
section#diary.dinner
  .container
    h3 MY DIARY
    .row.gy-4
      - @diaries.limit(8).each do |item|
        .col-lg-3.col-md-6
          .item
            p.date.mb-0 = item.created_at.strftime('%Y.%m.%d')
            p.hour = item.created_at.strftime('%H:%M')
            h4 = item.title
            p.desc = item.description

    .row.justify-content-between
      .col-md-12.text-center.align-items-center
        button.btn-more.mt-30 記録をもっと見る

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Arent
    meta name="viewport" content="width=device-width,initial-scale=1"
    link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  body
    = render 'partials/header'
    main#main
      = yield
    = render 'partials/footer'

app/views/partials/_footer.html.slim
footer#footer.footer
  .footer-content.position-relative
    .container
      .row
        .col-lg-12.col-md-3.footer-links
          = link_to "会員登録", "#"
          = link_to "運営会社", "#"
          = link_to "利用規約", "#"
          = link_to "個人情報の取扱について", "#"
          = link_to "特定商取引法に基づく表記", "#"
          = link_to "お問い合わせ", "#"
a.scroll-top.d-flex.align-items-center.justify-content-center[href="#"]
  i.bi.bi-arrow-up-short

app/views/partials/_header.html.slim
header#header.header.d-flex.align-items-center
  .container-fluid.container-xl.d-flex.align-items-center.justify-content-between
    = link_to root_path, class: "logo d-flex align-items-center"
      = image_tag 'logo.svg'
    i.mobile-nav-toggle.mobile-nav-show.bi.bi-list
    i.mobile-nav-toggle.mobile-nav-hide.d-none.bi.bi-x
    nav#navbar.navbar
      ul
        li
          = link_to root_path, class: "#{current_class?(root_path)}" do
            = image_tag "icons/icon_memo.svg"
            | 自分の記録
        li
          = link_to my_record_path, class: "#{current_class?(my_record_path)}" do
            = image_tag "icons/icon_challenge.svg"
            | チャレンジ
        li
          = link_to columns_path, class: "#{current_class?(columns_path)}" do
            = image_tag "icons/icon_info.svg"
            | お知らせ
        li.dropdown
          = image_tag "icons/icon_menu.svg"
          ul
            li
              = link_to "自分の記録", root_path, class: ""
            li
              = link_to "体重グラフ", my_record_path, class: ""
            li
              = link_to "目標", "#", class: ""
            li
              = link_to "選択中のコース", "#", class: ""
            li
              = link_to "コラム一覧", columns_path, class: ""
            li
              = link_to "設定", "#", class: ""
            - if current_user.present?
              li
                = link_to "ログアウト", destroy_user_session_path, method: :delete
            - else
              li
                = link_to "Login", new_user_session_path

app/views/users/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation[data-turbo-cache="false"]
    h2
      = I18n.t("errors.messages.not_saved",
      -                  count: resource.errors.count,
      -                  resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false }
    br